### ISSUE TITLE
testing approach

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/frontend-app#7]
In the application let's try separate 3 kinds of tests:

#### 1. unit tests for non-Flask-speficifc parts of code

This is to check any functions that are not related to Flask functionality, same as we would have done in any other unittest. 

#### 2. testing of app public interfaces with local flask client as in <http://flask.pocoo.org/docs/0.12/testing>

This checks the following interfaces:
```
/annual/
/quarterly/
/monthly/
/status/
/
```
The test should make sure the interface is callable and returns non-empty properly typed output. 
In theory can do that with urllib/requests (dirtier) or selenium (more complex), but for simple case like ours the suggestion is native testing mechanism described at <http://flask.pocoo.org/docs/0.12/testing>.

Tests 1 and 2 are for sure a part of Travis-CI suite. 

#### 3. integration(?) test for the app content 

With this test want to achive identity of the data delivered by the app and residing at parent repo. 

The files at parent repo are: 
- <https://raw.githubusercontent.com/epogrebnyak/mini-kep/master/data/processed/latest/dfa.csv>
- <https://raw.githubusercontent.com/epogrebnyak/mini-kep/master/data/processed/latest/dfq.csv>
- <https://raw.githubusercontent.com/epogrebnyak/mini-kep/master/data/processed/latest/dfm.csv>

The app calls to them are: 
- <http://mini-kep.herokuapp.com/annual/>
- <http://mini-kep.herokuapp.com/quarterly/>
- <http://mini-kep.herokuapp.com/monthly/>

This test may also be a data import validation procedure, and its result can go to ```\status``` json.

Not sure test 3 fits to Travis - it involves a web call to parent repo, which can slow down/break the CI.

**Comment by epogrebnyak** [comment]
Actual tests are kind of ahead the description: <https://github.com/epogrebnyak/mini-kep-app/tree/master/tests>. 

test_classes.py is type 1, test_views.py is type 2 and there is integration test of type 3.

@MadViper, what is your impression of the tests?

**Comment by epogrebnyak** [comment]
Вопросы к специалистам:

**[test_views.py](https://github.com/epogrebnyak/mini-kep-app/blob/master/tests/test_views.py):**
- [ ] кверить url приложения через urllib - хорошая практика или не очень? 
- [ ] хотим переделать тесты с [.app.test_client](http://flask.pocoo.org/docs/0.12/testing/), это будет лучше?
- [ ] проверка ```self.response.status_code == 200```?

**[test_integrity.py](https://github.com/epogrebnyak/mini-kep-app/blob/master/tests/test_integrity.py)**
- [ ] у нас есть 'интеграционный тест', который проверяет идентичность импортированных данных и данных откуда мы из взяли (из материанского репозитария). как он вам?

**все тесты:**
- [ ] любые комментарии насчет того что может резать глаз в репозитарии сейчас или поможет на будущее

**o незаконченных тестах, из предыдущей работы:**
- [ ] где-то читал, что для незаконченного теста (придумал идею теста, но не написал) надо поставить ```assert 0``` и пусть своим паданием сподвигнет к его написанию. Падающие тесты плохо, и я, например, незаконченный тест стал маркировать в skip или xfail (в pytest). Как правильно поступать с незаконченными тестами?

**Comment by epogrebnyak** [comment]
Testing example with [flask cookiecutter](https://github.com/JackStouffer/cookiecutter-Flask-Foundation/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tests/test_urls.py) also uses ```app.test_client()```

**Comment by MadViper** [comment]
Splitting tests into 3 high-level types is a really good idea.

(in future) I also strongly recommend writing non-flask related unit tests before or immediately after the code itself is written this approach forces developers to write testable code and eliminates needs for the refactoring because of the non-testability.

I would recommend using approach proposed on the flask official web page rather the requests and urllib

Integrity tests seems ok at this point (I am not too familiar with the inner working of the app though)

About "unfinished" tests I generally use the same approach I just skip the tests and put something like "not implemented yet" in the reason that is passed as a string to the skip method.

**Comment by epogrebnyak** [comment]
Thanks for review! How do you skip the test usually? Just comment it out?

**Comment by MadViper** [comment]
No no, I generally use unittest library and it contains unittest.skip decorator.

See: [26.4.6. Skipping tests and expected failures](https://docs.python.org/3/library/unittest.html)

**Comment by alexeykryukov** [comment]
Общие поинты по коду: 
1) настроить codestyle а именно. 
	a) отступы классов - ожидается два раделителя вместо одного(пример: test_views.py между 9 и 11 строкой только один отступ, надо два)
	б) отступы методов. тоже самое. пример - apps/classes > def get_parent_repo_url и def download_file_contents
	в) test_cases.py строчки 15 и 31 > 120 characters
2) best practices рекомендуют придерживаться https://www.python.org/dev/peps/pep-0257/ структуры docstrings. 
некоторым методам было бы полезно описать параметры и опционально примеры(особенно для helper методов). 
3) структура приложения: 
	а) возможно apps нужно переименовать в src. если подразумевается, что это будет не одно приложение - лучше сразу из разбить на отдельные и сопровождать раздельно. 
	б) лучше разбивать приложения на отдельные маленькие модули, а не стараться поместить всю логику в один файл.
	при этом очень важно давать осмысленное и логичное именование переменным, методам и классам. 
	например: файл apps/classes.py. два файла можно вынести в отдельные файлы. тоже самое с методами. похоже, что это вспомогательные или мервисные методы - можно вынести в отдельный helper class. структура получится следующей:
	src
	--business
	----files
	------_init_.py
	------LocalFile.py
	------RemoteFile.py
	----helpers
	------_init_.py
	------RepositoryHelper.py
	в) тоже самое с views; лучше сразу разбивать на отдельные части
	src
	--views
	----_init_.py
	----home.py
	----status.py
	----webhooks.py
	... 
	имеет смысл так делать, если подразумевается, что в последующем файлы будут расширятся и у каждой сущности будет более объемный интерфейс.
	г) тут же - from_json, to_json. это насколько я понял методы для работы file <-> json и я бы вынес это в отдельный модуль - мне кажется в дальнейшем он будет использоваться помимо view.
	д) пример: apps/classes.py строчка 5. подобные штуки надо выносить в config files. в реальной жизни получается несколько конфигов - dev, prod, test и т.д. 
	в качестве конфига настоятельно рекомендую использовать YAML

-------------------
test_views.py
1) так же, лучше разбить классы на разные файлы. и для каждого endpoint в конкретном файле будут как success result тесты, так и check error тесты(если статус ответа 4xx, 5xx). 
2) setUp для всех тестов практически одинаковые и получается, что очень много duplicate code(различается только url_for параметр). имеет смысл вынести эту логику в отдельный метод(что то вроде executeGetRequest с параметром path) и использовать его для всех тестов. а можно и создать базовый test class для GET методов например и вынести эту логику туда. в тестах рекомендуется иметь строки вроде application.get(path) или application.post(path, body) 
3) по поводу urllib - я бы рекомендовал использовать полные пути без использования сторонних builder. это во первых наглядно, во вторых не приходится зависеть от сторонних утилит. 
например. предположим, что есть метод application.get(path) и мы ему передаем например "/api/v1/status".
4) да, flack test_client отличное решение. как раз позволит сделать то, что описал выше. пример взял с доки: 
self.app.post('/login', data=dict(
        username=username,
        password=password
    ), follow_redirects=True)
5) да, проверка status_code это норм. ну разумеется, надо проверять еще response body, если response не пустой.

--------------------
1) test_identity - это unit test. test_status_json - integration test. в целом лучше вынести логику для работы с csv в отдельный файл и покрыть unit тестами его.
2) в целом тест ок

--------------------

незаконченные тесты: ну assert 0 не оч хорошая практика, тесты должны быть green.
практика такая, что такие тесты пропускаются skip с указанием причины - что тест с флагом TO_IMPLEMENT и указывается что вкратце он должен делать. 
в целом, skipped надо чинить ASAP и в идеале их не должно быть. skipped тесты и должны стимулировать их закончить.  
так же рекомендую использовать code coverage утилиты - хорошо помогают выявить куски кода, которые нуждаются в покрытии тестами

**Comment by epogrebnyak** [comment]
@alexeykryukov , спасибо за детальный review, как водится с тестами - начинаем о них, идем к улучшению структуры программы, спасибо посмотрели на вопрос под этим углом.

**Comment by epogrebnyak** [comment]
Все что касается практики разработки и к чему что приводит - тоже изучаем и обдумываем. Просьба прокомментировать про yaml - всегда ли это хорошо?  Не проще ли пользоваться чем-то внутренних переменных, возможно в отдельном файле даже (пример [отсюда](http://flask.pocoo.org/docs/0.12/config/)): 

```python 
class Config(object):
    DEBUG = False
    TESTING = False
    DATABASE_URI = 'sqlite://:memory:'

class ProductionConfig(Config):
    DATABASE_URI = 'mysql://user@localhost/foo'

class DevelopmentConfig(Config):
    DEBUG = True

class TestingConfig(Config):
    TESTING = True
```

**Comment by alexeykryukov** [comment]
@epogrebnyak  да, такой подход тоже хороший, когда требуется наследование конфигураций(или расширение) + можно добавлять кастомную runtime логику. успешно использую такую практику на nodejs проектах. там довольно удачно это реализовано через config package. и получается, что самый большой default config, а production и все остальные довольно небольшие. 

единственный по мне так существенный недостаток тут, что конфиг хранится в скрипт файлах - .py. и например test coverage утилиты из будут помечать в uncovered, будет так скажем бросаться в глаза это, хотя возможно это и мелочь.

в целом ваш подход описанных выше - good practice для flask, django проектов. в дополнение оч рекомендую все таки default(base), production, development(local) конфиги хранить в отдельных файлах. это очень наглядно и можно легко ориентироваться в проекте

**Comment by epogrebnyak** [comment]
note: not testing <config.py> at rot of repo now
